default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: admin
  password: n1502803a

development:
  <<: *default
  database: mis21_sms_app_development

test:
  <<: *default
  database: mis21_sms_app_test

production:
  <<: *default
  database: mis21_sms_app_production
